name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D GitHub profile image
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Generate the 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.10.0

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "Generated 3D contribution graph" || echo "No changes to commit"
          git push

